name: Dispatch Update to Browser Repo

on:
  pull_request:
    types: [closed]
    branches:
      - v2
      
  workflow_dispatch:

jobs:
  dispatch:
    # Run this job if the PR was merged OR if it was triggered manually
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch update event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SYNC_PAT }}
          repository: biase-d/titledb-browser
          event-type: nx-performance-updated
